name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2 #checkout-a project source code da ga workflow moze koristit
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: npm install #ime step-a
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test #maknuo ove testove tako da se brze deploya na heroku,, dok ne skuzim u cemu je problem s herokuom onda cu ih vratit
        run: npm test
      - name: e2e tests
        uses: cypress-io/github-action@v2 #prije bilo bez crtice ('-')
        with:
          command: npm run test:e2e #specificira kako runnat test
          start: npm run start-prod #skripta koja starta server
          wait-on: http://localhost:5000 #kaze da prije nego se runnaju testovi, server se mora pokrenut na toj adresi

      - name: Deploy to heroku
        if: ${{ github.event_name == 'push' }} #da se deploya samo ako je push a ne pull_request npr, kad se pull_request merge-a, automatski se triggera push
        #uses: actions/checkout@v2 #prije bilo bez ovog
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "part11-app" #Must be unique in Heroku
          heroku_email: "bornaparo@gmail.com"
          healthcheck: "https://part11-app.herokuapp.com/health" #kao check neki da vidi ako aplikacija radi nakon deploymenta a da ne moras manualno checkat
          checkstring: "ok" #provjerava ako je ovo string koji vraca taj check
          rollbackonhealthcheckfailed: true #automatski ce se vratit na zadnju verziju koja je radila ako ne pass-a ovaj healthcheck
      - uses: actions/checkout@v2 #za svaki slucaj jer je njemu bacao error
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }} #samo kad se push-a na master branch, inace ti ne trebaju verzije (tagovi)
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
