name: Deployment pipeline

on:
  push:
    branches:
      - master
      
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2 #checkout-a project source code da ga workflow moze koristit
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: npm install #ime step-a
        run: npm install
      - name: lint
        run: npm run eslint
      
  
