name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job: #da vidim sta ce ispisat
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: provjera commit poruke
        env:
          #COMMIT_PROVJERA: ${{ toJson(github.event.commits.*.message) }}
          #X: ${{ join(toJson(github.event.commits.*.message), ' ') }}
          X: ${{ contains(join(toJson(github.event.commits.*.message), ' '), 'skip') }}
        run: echo "$X"
